external_components:
  - source: github://Jopand/esphome_components@main
    refresh: 0s

packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files:
      ### INPUT REGISTER FILES ###
      - components/nilan/holding/221.yaml
      - components/nilan/holding/1001.yaml
      - components/nilan/holding/1002.yaml
      ### HOLDING REGISTER FILES ###
      - components/nilan/holding/200.yaml
      - components/nilan/holding/201.yaml
      - components/nilan/holding/400.yaml
      - components/nilan/holding/601.yaml
      - components/nilan/holding/1002.yaml
      - components/nilan/holding/1003.yaml
      - components/nilan/holding/1004.yaml

nilan:

sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Exhaust temperature"
    id: nilan_exhaust_temp_t3
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 203
    filters:
      - multiply: 0.01
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Outlet temperature"
    id: nilan_outlet_temp_t4
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 204
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet (after heater) temperature"
    id: nilan_inlet_temp_t7
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 207
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Outdoor temperature"
    id: nilan_outdoor_temp_t8
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 208
    filters:
      - multiply: 0.01

text_sensor:
  - platform: template
    name: "Air Quality Index Humidity (AQI)"
    id: aqi_humidity
    icon: mdi:water-percent 

climate:
  - platform: nilan
    name: Nilan
    current_temp_sensor_id: nilan_inlet_temp_t7
    target_temp_sensor_id: nilan_target_temperature_set
    fan_speed_sensor_id: nilan_ventilation_speed_set
    mode_select_id: nilan_set_operation_mode
    
button:
  - platform: output
    name: Reset alarm
    id: nilan_reset_alarm_button
    output: nilan_reset_alarm
    duration: 5s