external_components:
  - source: github://Jopand/esphome_components@main
    refresh: 0s

packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files:
      ### INPUT REGISTER FILES ###
      - components/nilan/input/203.yaml
      - components/nilan/input/204.yaml
      - components/nilan/input/207.yaml
      - components/nilan/input/208.yaml
      - components/nilan/input/221.yaml
      - components/nilan/input/1001.yaml
      ### HOLDING REGISTER FILES ###
      - components/nilan/holding/200.yaml
      - components/nilan/holding/201.yaml
      - components/nilan/holding/400.yaml
      - components/nilan/holding/1002.yaml
      - components/nilan/holding/1003.yaml
      - components/nilan/holding/1004.yaml

nilan:

sensor:
  - platform: template
    name: "Calculated difference exhaust and inlet"
    id: nilan_calculated_value_inlet_exhaust
    icon: "mdi:thermometer"
    unit_of_measurement: °C
    update_interval: 10s
    lambda: 'return id(nilan_exhaust_temp_t3).state - id(nilan_inlet_temp_t7).state;'

text_sensor:
  - platform: template
    name: "Air Quality Index Humidity (AQI)"
    id: nilan_aqi_humidity
    icon: mdi:water-percent 

climate:
  - platform: nilan
    name: Nilan
    id: nilan_climate
    current_temp_sensor_id: nilan_inlet_temp_t7
    target_temp_sensor_id: nilan_target_temperature_set
    fan_speed_sensor_id: nilan_ventilation_speed_set
    mode_select_id: nilan_set_operation_mode