packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files: 
      - components/nilan/all.yaml
      ### INPUT REGISTER FILES ###
      - components/nilan/input/1204.yaml
      ### HOLDING REGISTER FILES ###
      - components/nilan/holding/1200.yaml
      - components/nilan/holding/1201.yaml
      - components/nilan/holding/1202.yaml
      - components/nilan/holding/1203.yaml
      - components/nilan/holding/1204.yaml
      - components/nilan/holding/1700.yaml
      - components/nilan/holding/1701.yaml
    refresh: 0s

binary_sensor:
#########################
#### INPUT REGISTERS ####
#########################    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Door open"
    id: nilan_door_open
    register_type: read
    address: 102
    bitmask: 1
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Motor thermo fuse"
    id: nilan_motor_thermo_fuse
    register_type: read
    address: 104
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heating surface frost/overheat"
    id: nilan_heating_surface_frost_oerheat
    register_type: read
    address: 105
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Airflow monitor"
    id: nilan_airflow_monitor
    register_type: read
    address: 106
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Low pressure switch"
    id: nilan_low_pressure
    register_type: read
    address: 108
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function 2"
    id: nilan_user_function_2
    register_type: read
    address: 113
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air damper closed"
    id: nilan_damper_closed
    register_type: read
    address: 114
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air damper opened"
    id: nilan_damper_opened
    register_type: read
    address: 115
    bitmask: 1