packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files:
      - components/nilan/cts602-light.yaml
      ### INPUT REGISTER FILES ###
      - components/nilan/input/102.yaml
      - components/nilan/input/104.yaml
      - components/nilan/input/106.yaml
      - components/nilan/input/107.yaml
      - components/nilan/input/108.yaml
      - components/nilan/input/201.yaml
      - components/nilan/input/210.yaml
      - components/nilan/input/215.yaml
      ### HOLDING REGISTER FILES ###
      - components/nilan/holding/123.yaml
      - components/nilan/holding/125.yaml
      - components/nilan/holding/1700.yaml
      - components/nilan/holding/1701.yaml
    refresh: 0s

sensor:
- id: !extend nilan_protocol_node_address
  address: 50