packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files:
      - components/nilan/basic.yaml
      ### INPUT REGISTER FILES ###
      - components/nilan/input/0.yaml
      - components/nilan/input/1.yaml
      - components/nilan/input/100.yaml
      - components/nilan/input/101.yaml
      - components/nilan/input/103.yaml
      - components/nilan/input/105.yaml
      - components/nilan/input/113.yaml
      - components/nilan/input/114.yaml
      - components/nilan/input/115.yaml
      - components/nilan/input/200.yaml
      - components/nilan/input/209.yaml
      - components/nilan/input/222.yaml
      - components/nilan/input/400.yaml
      - components/nilan/input/401.yaml
      - components/nilan/input/402.yaml
      - components/nilan/input/403.yaml
      - components/nilan/input/404.yaml
      - components/nilan/input/405.yaml
      - components/nilan/input/406.yaml
      - components/nilan/input/407.yaml
      - components/nilan/input/408.yaml
      - components/nilan/input/409.yaml
      - components/nilan/input/1000.yaml
      - components/nilan/input/1002.yaml
      - components/nilan/input/1003.yaml
      - components/nilan/input/1100.yaml     
      - components/nilan/input/1101.yaml
      - components/nilan/input/1102.yaml
      - components/nilan/input/1103.yaml
      - components/nilan/input/1104.yaml
      - components/nilan/input/1200.yaml
      - components/nilan/input/1201.yaml
      - components/nilan/input/1202.yaml
      - components/nilan/input/1203.yaml
      - components/nilan/input/1204.yaml
      - components/nilan/input/1205.yaml
      - components/nilan/input/1206.yaml
      ### HOLDING REGISTER FILES ###
      - components/nilan/holding/0.yaml
      - components/nilan/holding/100.yaml
      - components/nilan/holding/101.yaml
      - components/nilan/holding/102.yaml
      - components/nilan/holding/103.yaml
      - components/nilan/holding/104.yaml
      - components/nilan/holding/105.yaml
      - components/nilan/holding/122.yaml
      - components/nilan/holding/126.yaml

      - components/nilan/holding/1105.yaml
      - components/nilan/holding/1200.yaml
      - components/nilan/holding/1201.yaml
      - components/nilan/holding/1202.yaml
      - components/nilan/holding/1203.yaml
      - components/nilan/holding/1204.yaml
      - components/nilan/holding/1205.yaml
      - components/nilan/holding/1206.yaml
      - components/nilan/holding/1207.yaml
    refresh: 0s

binary_sensor:
  - platform: template
    id: nilan_bypass_state
    name: Bypass state
    device_class: opening