packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files: 
      - components/nilan/comfort.yaml
      ### INPUT REGISTER FILES ###
      - components/nilan/input/201.yaml
    refresh: 0s

sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet (before heater) temperature"
    id: nilan_inlet_temp_t2
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 202
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Condenser temperature"
    id: nilan_condenser_temp_t5
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 205
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Evaporator temperature"
    id: nilan_evap_temp_t6
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 206
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot weater top temperature"
    id: nilan_top_temp_t11
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 211
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water bottom temperature"
    id: nilan_bottom_temp_t12
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 212
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "EK return temperature"
    id: nilan_return_temp_t13
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 213
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "EK supply temperature"
    id: nilan_supply_temp_t14
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 214
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "AUX temperature"
    id: nilan_aux_temp_t16
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 216
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Preheater temperature"
    id: nilan_preheat_temp_t17
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 217
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Pressure pibe temperature"
    id: nilan_prepibe_temp_t18
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 218
    filters:
      - multiply: 0.01
      
###########################
#### HOLDING REGISTERS ####
###########################

binary_sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water boiling"
    id: nilan_hot_water_boiling
    register_type: read
    address: 109

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water 3-way valve position"
    id: nilan_3_way_position
    register_type: read
    address: 110

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hotgas defrost"
    id: nilan_hotgas_defrost
    register_type: read
    address: 111

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Defrost termostat"
    id: nilan_defrost_termostat
    register_type: read
    address: 112

###########################
#### HOLDING REGISTERS ####
###########################
    

        

    

    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heating selected"
    id: nilan_air_heat_selected
    register_type: holding
    address: 105
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Compressor"
    id: nilan_compressor
    register_type: holding
    address: 109

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Compressor 2"
    id: nilan_compressor_2
    register_type: holding
    address: 110 

#text_sensor:

#######################################################################      
#### WARNING - IF THERE ARE ANY SPECIAL CHARACTERS ON THE DISPLAY, ####
#### ENABLING THESE SENSORS WILL CRASH THE PROGRAM WHEN PUBLISHING ####
#######################################################################
#  - platform: modbus_controller
#    modbus_controller_id: nilan_modbus_controller
#    name: "Display upper line"
#    id: nilan_display_upper_line
#    force_new_range: true
#    register_type: read
#    register_count: 4
#    response_size: 8
#    address: 2002
    
#  - platform: modbus_controller
#    modbus_controller_id: nilan_modbus_controller
#    name: "Display lower line"
#    id: nilan_display_lower_line
#    force_new_range: true
#    register_type: read
#    register_count: 4
#    response_size: 8
#    address: 2007
