sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Bus version"
    id: nilan_bus_version
    skip_updates: 60
    internal: true
    accuracy_decimals: 0
    entity_category: diagnostic
    register_type: read
    address: 0