binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function"
    id: nilan_user_function
    register_type: read
    address: 100
    bitmask: 1