sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function"
    id: nilan_user_function
    accuracy_decimals: 0
    register_type: read
    address: 100