sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Actual on/off state"
    id: nilan_actual_on_off_state
    accuracy_decimals: 0
    register_type: read
    address: 1000