sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Seconds in state"
    id: nilan_seconds_in_state
    accuracy_decimals: 0
    register_type: read
    address: 1003