sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Seconds in state"
    id: nilan_seconds_in_state
    unit_of_measurement: s
    accuracy_decimals: 0
    device_class: duration
    register_type: read
    address: 1003