binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Smoke alarm"
    id: nilan_smoke_alarm
    register_type: read
    address: 103
    bitmask: 1