binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Airflow monitor"
    id: nilan_airflow_monitor
    register_type: read
    address: 106
    bitmask: 1