binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water 3-way valve position"
    id: nilan_hot_3_way_valve_position
    register_type: read
    address: 110
    bitmask: 1