sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Days since last filter change alarm"
    id: nilan_days_since_last_filter_alarm
    unit_of_measurement: 'days'
    accuracy_decimals: 0
    register_type: read
    address: 1103
    icon: mdi:fan