sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Days to next filter change alarm"
    id: nilan_days_to_next_filter_alarm
    unit_of_measurement: 'days'
    accuracy_decimals: 0
    register_type: read
    address: 1104