sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Controller temperature"
    id: nilan_controller_temp_t0
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    address: 200
    filters:
      - multiply: 0.01