sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heating surface temperature"
    id: nilan_heater_temp_t9
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 209
    filters:
      - multiply: 0.01
