sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "External room temperature"
    id: nilan_extern_temp_t10
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 210
    filters:
      - multiply: 0.01