sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water top temperature"
    id: nilan_top_temp_t11
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 211
    filters:
      - multiply: 0.01