sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Room temperature"
    id: nilan_room_temp_t15
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 215
    filters:
      - multiply: 0.01