sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Application Hardware Id"
    id: nilan_application_hardware_id
    skip_updates: 60
    accuracy_decimals: 0
    entity_category: diagnostic
    register_type: read
    address: 5