sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Protocol node address"
    id: nilan_protocol_node_address
    accuracy_decimals: 0
    register_type: holding
    address: 0