binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heat circulation pump"
    id: nilan_air_heat_circulation_pump
    register_type: holding
    address: 104