binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heating selected"
    id: nilan_air_heat_selected
    register_type: holding
    address: 105