binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heater relay 1"
    id: nilan_air_heater_relay_1
    register_type: holding
    address: 106