binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hotgas valve - heat"
    id: nilan_hotgas_valve_heat
    register_type: holding
    address: 112