binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hotgas valve - cool"
    id: nilan_hotgas_valve_cool
    register_type: holding
    address: 113