binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air condenser active"
    id: nilan_air_condenser_active
    register_type: holding
    address: 114
    on_state: 
    - lambda: !lambda |-
        id(nilan_condenser_state).publish_state(true);    