binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water heater"
    id: nilan_hot_water_heater
    register_type: holding
    address: 116