binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function active"
    id: nilan_user_function_active
    register_type: holding
    address: 123