binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Defrost function active"
    id: nilan_defrost_function_active
    register_type: holding
    address: 125
