sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heater capacity"
    id: nilan_air_heater_capacity
    unit_of_measurement: '%'
    icon: "mdi:percent"
    accuracy_decimals: 0
    register_type: holding
    address: 202
    filters:
      - multiply: 0.01