sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Calibrate DPT"
    id: nilan_calibrate_dpt
    accuracy_decimals: 0
    register_type: holding
    address: 2200